export const UPPDATE_HOME_DATA = 'UPPDATE_HOME_DATA'
export const UPPDATE_PRODUCT_DATA = 'UPPDATE_PRODUCT_DATA'
export const ADD_PRODUCT_DATA = 'ADD_PRODUCT_DATA'

export const ADD_TAPITA_CMT = 'ADD_TAPITA_CMT'
export const ADD_TAPITA_FEATURE = 'ADD_TAPITA_FEATURE'

export const ADD_CART_DATA = 'ADD_CART_DATA';
export const WISHLIST_DATA = 'WISHLIST_DATA';
export const LIST_REVIEWS = 'LIST_REVIEWS';
export const ADD_REVIEW_DATA = 'ADD_REVIEW_DATA'

