export const APP_CONFIG_SIMICART = ''
export const MERCHANT_CONFIG = 'storeviews/default'
export const HOME = 'homes/lite'
export const EDIT_TODO = 'EDIT_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const COMPLETE_ALL = 'COMPLETE_ALL'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
